import {NgModule} from '@angular/core';
import {RouterModule,Routes} from '@angular/router';
import {PagesComponent} from './pages.component';
import {QAndASummaryComponent} from './q-and-asummary/q-and-asummary.component';
import {QAndACategorysummaryComponent} from './q-and-a-categorysummary/q-and-a-categorysummary.component';
import {GenralreportComponent} from './genralreport/genralreport.component';
import {InfoKitComponent} from './infokit/infokit.component';
import {ScholarshipmanagementComponent} from './scholarshipmanagement/scholarshipmanagement.component';
import {PitchDeskComponent} from './pitch-desk/pitch-desk.component';
import {ReportsystemComponent} from './reportsystem/reportsystem.component';
import {CareerPlannerComponent} from './career-planner/career-planner.component';
import {JobSitesComponent} from './career-planner/job-sites/job-sites.component';
import {CourseListComponent} from './course-list/course-list.component';
import {UniversityListComponent} from './course-list/university-list/university-list.component';
import {UnifinderSubjectComponent} from './course-list/unifinder-subject/unifinder-subject.component';
import {RolesmanagementComponent} from './rolesmanagement/rolesmanagement.component';
import {AdvisorChatComponent} from './advisor-chat/advisor-chat.component';
import {PromptEditorComponent} from './prompt-editor/prompt-editor.component';

const routes: Routes = [
    {
        path: "",
        component: PagesComponent,
        children: [
            {path: "",redirectTo: "userdashboard",pathMatch: "full"},
            {path: "users/add-users",loadComponent: () => import("./users/users.component").then(m => m.UsersComponent)},
            {path: "users/assign-institutions",loadComponent: () => import("./users/institution/institution.component").then(m => m.InstitutionComponent)},
            {path: "subscription",loadComponent: () => import("./subscription/subscription.component").then(m => m.SubscriptionComponent)},
            {path: "dashboard",loadComponent: () => import("./dashboard/dashboard.component").then(m => m.DashboardComponent)},
            {path: "subscribers",loadComponent: () => import("./subscribers/subscribers.component").then(m => m.SubscribersComponent)},
            {path: "subscribers/add-subscriber",loadComponent: () => import("./subscribers/add-subscriber/add-subscriber.component").then(m => m.AddSubscriberComponent)},
            {path: "subscribers/datavalidator",loadComponent: () => import("./subscribers/datavalidator/datavalidator.component").then(m => m.DatavalidatorComponent)},
            {path: "subscribers/:id",loadComponent: () => import("./subscribers/subscribers.component").then(m => m.SubscribersComponent)},
            {path: "filtered-questions",loadComponent: () => import("./questions/questions.component").then(m => m.QuestionsComponent)},
            {path: "subscribers/editprofile/:id",loadComponent: () => import("./subscriberseditprofile/subscriberseditprofile.component").then(m => m.SubscriberseditprofileComponent)},
            {path: "quiz",loadChildren: () => import("./Quiz/quiz.module").then((m) => m.QuizModule),},
            {path: "reading",loadChildren: () => import("./reading/reading.module").then(m => m.ReadingModule)},
            {path: "creditchat",loadComponent: () => import("./chat/creditchat/creditchat.component").then(m => m.CreditchatComponent)},
            {path: "investor",loadChildren: () => import("./investor/investor.module").then(m => m.InvestorModule)},
            {path: "company",loadChildren: () => import("./company-list/company-list.module").then(m => m.CompanyListModule)},
            {path: "reading",loadChildren: () => import("./reading/reading.module").then(m => m.ReadingModule)},
            {path: "suggested",loadChildren: () => import("./suggested-add-question/suggested-add-question.module").then(m => m.SuggestedAddQuestionModule)},
            {path: "creditchat",loadComponent: () => import("./chat/creditchat/creditchat.component").then(m => m.CreditchatComponent)},
            {path: "ticket",loadComponent: () => import("./chat/ticketlist/ticketlist.component").then(m => m.TicketlistComponent)},
            {path: "chat",loadComponent: () => import("./chat/chathistory/chathistory.component").then(m => m.ChathistoryComponent)},
            {path: "reports",loadComponent: () => import("./report/report.component").then(m => m.ReportComponent)},
            {path: "supportchat",loadComponent: () => import("./tickets/supportchat/supportchat.component").then(m => m.SupportchatComponent)},
            {path: "ticketslist",loadComponent: () => import("./tickets/ticketsticketlist/ticketsticketlist.component").then(m => m.TicketsticketlistComponent)},
            {path: "countrymanagement",loadComponent: () => import("./countrymanagement/countrymanagement.component").then(m => m.CountrymanagementComponent)},
            {path: "addcolleges",loadComponent: () => import("./Collegeuser/addcollege/addcollege.component").then(m => m.AddcollegeComponent)},
            {path: "addcolleges/addcoupen",loadComponent: () => import("./Collegeuser/addcoupen/addcoupen.component").then(m => m.AddcoupenComponent)},
            {path: "addpartner",loadComponent: () => import("./partneruser/addpartner/addpartner.component").then(m => m.AddpartnerComponent)},
            {path: "addpartner/addcoupen",loadComponent: () => import("./partneruser/addpartnercoupen/addpartnercoupen.component").then(m => m.AddpartnercoupenComponent)},
            {path: "ticketslist",loadComponent: () => import("./tickets/ticketsticketlist/ticketsticketlist.component").then(m => m.TicketsticketlistComponent)},
            {path: "userdashboad",loadComponent: () => import("./user-dashboard/user-dashboard.component").then(m => m.UserDashboardComponent)},
            {path: "revenuedashboard",loadComponent: () => import("./revenuedashboard/revenuedashboard.component").then(m => m.RevenuedashboardComponent)},
            {path: "qareports",loadComponent: () => import("./qareports/qareports.component").then(m => m.QareportsComponent)},
            {path: "addcoupen",loadComponent: () => import("./Collegeuser/addcoupen/addcoupen.component").then(m => m.AddcoupenComponent)},
            {path: "profile",loadComponent: () => import("./myprofile/myprofile.component").then(m => m.MyprofileComponent)},
            {path: "userdashboad",loadComponent: () => import("./user-dashboard/user-dashboard.component").then(m => m.UserDashboardComponent)},
            {path: "data/help-cat",loadComponent: () => import("./help-cat/help-cat.component").then(m => m.HelpCatComponent)},
            {path: "data/help",loadComponent: () => import("./help/help.component").then(m => m.HelpComponent)},
            {path: "data/faq-cat",loadComponent: () => import("./faq-cat/faq-cat.component").then(m => m.FaqCatComponent)},
            {path: "data/faq",loadComponent: () => import("./faq/faq.component").then(m => m.FaqComponent)},
            {path: "resources",loadComponent: () => import("./resources/resources.component").then(m => m.ResourcesComponent)},
            {path: "userdashboard",loadComponent: () => import("./user-dashboard/user-dashboard.component").then(m => m.UserDashboardComponent)},
            {path: "revenuedashboard",loadComponent: () => import("./revenuedashboard/revenuedashboard.component").then(m => m.RevenuedashboardComponent)},
            {path: "qareports",loadComponent: () => import("./qareports/qareports.component").then(m => m.QareportsComponent)},
            {path: "review/preapplication",loadComponent: () => import("./preapplicationreview/preapplicationreview.component").then(m => m.PreapplicationreviewComponent)},
            {path: "review/preappcat",loadComponent: () => import("./preappcat/preappcat.component").then(m => m.PreappcatComponent)},
            {path: "review/module/:id",loadComponent: () => import("./reviewsubmodule/reviewsubmodule.component").then(m => m.ReviewsubmoduleComponent)},
            {path: "review/questions/:module/:submodule",loadComponent: () => import("./reviewquestions/reviewquestions.component").then(m => m.ReviewquestionsComponent)},
            {path: "review/dashboard",loadComponent: () => import("./reviewdashboard/reviewdashboard.component").then(m => m.ReviewdashboardComponent)},
            {path: "review/user",loadComponent: () => import("./reviewuser/reviewuser.component").then(m => m.ReviewuserComponent)},
            {path: "review/addquestion",loadComponent: () => import("./addreviewquestion/addreviewquestion.component").then(m => m.AddreviewquestionComponent)},
            {path: "review/admin/user",loadComponent: () => import("./reviewuseradmin/reviewuseradmin.component").then(m => m.ReviewuseradminComponent)},
            {path: "student",loadComponent: () => import("./student/student.component").then(m => m.StudentComponent)},
            {path: "studentlist",loadComponent: () => import("./studentlist/studentlist.component").then(m => m.StudentlistComponent)},
            {path: "leaddashboard",loadComponent: () => import("./leaddashboard/leaddashboard.component").then(m => m.LeaddashboardComponent)},
            {path: "creditsheet",loadComponent: () => import("./creditsheet/creditsheet.component").then(m => m.CreditsheetComponent)},
            {path: "coupenmanagement",loadComponent: () => import("./coupenmanagement/coupenmanagement.component").then(m => m.CoupenmanagementComponent)},
            {path: "politician-insights",loadComponent: () => import("./add-politician-insights/add-politician-insights.component").then(m => m.AddPoliticianInsightsComponent)},
            {path: "mycoupon",loadComponent: () => import("./mycoupon/mycoupon.component").then(m => m.MycouponComponent)},
            {path: "collegemanagement",loadComponent: () => import("./collegemanagement/collegemanagement.component").then(m => m.CollegemanagementComponent)},
            {path: "review/organization",loadComponent: () => import("./revieworganization/revieworganization.component").then(m => m.RevieworganizationComponent)},
            {path: "couponmanagement",loadComponent: () => import("./coupenmanagement/coupenmanagement.component").then(m => m.CoupenmanagementComponent)},
            {path: "couponmanagement",loadComponent: () => import("./coupenmanagement/coupenmanagement.component").then(m => m.CoupenmanagementComponent)},
            {path: "events",loadComponent: () => import("./events/events.component").then(m => m.EventsComponent)},
            {path: "subscription-college-view",loadComponent: () => import("./subscription/college-subscription-view/college-subscription-view.component").then(m => m.CollegeSubscriptionViewComponent)},
            {path: "subscription-student-view",loadComponent: () => import("./subscription/student-subscription-view/student-subscription-view.component").then(m => m.StudentSubscriptionViewComponent)},
            {path: "subscription-history",loadComponent: () => import("./subscription/subscription-history/subscription-history.component").then(m => m.SubsriptionHistoryComponent)},
            {path: "addtutorial",loadComponent: () => import("./addtutorials/addtutorials.component").then(m => m.AddtutorialsComponent)},
            {path: "addstory",loadComponent: () => import("./addstories/addstories.component").then(m => m.AddStoriesComponent)},
            {path: "activeleadlist/:coupenid",loadComponent: () => import("./coupenmanagement/coupenleadlist/coupenleadlist.component").then(m => m.CoupenleadlistComponent)},
            {path: "registereventuser",loadComponent: () => import("./registereventusers/registereventusers.component").then(m => m.RegistereventusersComponent)},
            {path: "registereventuser/:eventid",loadComponent: () => import("./registereventusers/registereventusers.component").then(m => m.RegistereventusersComponent)},
            {path: "questionsummary",component: QAndASummaryComponent},
            {path: "questioncategorysummary",component: QAndACategorysummaryComponent},
            {path: "generalreport",component: GenralreportComponent},
            {path: "scholarshipmanagement",component: ScholarshipmanagementComponent},
            {path: "startup",component: InfoKitComponent},
            {path: "pitch-deck",component: PitchDeskComponent},
            {path: "job-site",component: JobSitesComponent},
            {path: "career-planner",component: CareerPlannerComponent},
            {path: "repotsystem",component: ReportsystemComponent},
            {path: "university-list",component: UniversityListComponent},
            {path: "unifinder-subject",component: UnifinderSubjectComponent},
            {path: "prompt-editor",component: PromptEditorComponent},
            {path: "landing-page",loadChildren: () => import('./landing-page/landing-page.module').then(m => m.LandingPageModule)},
            {path: "repotsystemchat",loadComponent: () => import("./reportsysetemchat/reportsysetemchat.component").then(m => m.ReportsysetemchatComponent)},
            {path: "language-hub",loadChildren: () => import("./language-hub/language-hub.module").then(m => m.LanguageHubModule)},
            {path: "certification",loadComponent: () => import("./certification/certification.component").then(m => m.CertificationComponent)},
            {path: "enterprise-subscription",loadComponent: () => import("./enterprise-subscription/enterprise-subscription.component").then(m => m.EnterpriseSubscriptionComponent)},
            {path: "certificationuserlist/:moduleid",loadComponent: () => import("./certificationuserlist/certificationuserlist.component").then(m => m.CertificationuserlistComponent)},
            {path: "user-tracking",loadComponent: () => import("./user-tracking/user-tracking.component").then(m => m.UserTrackingComponent)},
            {path: "course-list",component: CourseListComponent},
            {path: "whitelabel",loadComponent: () => import("./whitelabel/whitelabel.component").then(m => m.WhitelabelComponent)},
            {path: "promomailer",loadComponent: () => import("./promomailer/promomailer.component").then(m => m.PromomailerComponent)},
            {path: "academic-tools",loadChildren: () => import("./academic-tools/academic-tools.module").then((m) => m.AcademicToolsModule)},
            {path: "foundersacadamic",loadComponent: () => import("./founderstool/addacademicvedio/addacademicvedio.component").then(m => m.AddacademicvedioComponent)},
            {path: "investorpitchtraining",loadComponent: () => import("./founderstool/investorpitchtraining/investorpitchtraining.component").then(m => m.InvestorpitchtrainingComponent)},
            {path: "startupglossary",loadComponent: () => import("./founderstool/startupglossary/startupglossary.component").then(m => m.StartupglossaryComponent)},
            {path: "contributors",loadChildren: () => import("./contributions-program/contributions-program.module").then(m => m.ContributionsProgramModule)},
            {path: "talent-connect",loadChildren: () => import("./talent-connect/talent-connect.module").then(m => m.TalentConnectModule)},
            {path: "requirement",loadChildren: () => import("./requirement/requirement.module").then(m => m.RequirementModule)},
            {path: "country-insights",loadChildren: () => import("./founderstool/country-insights/country-insights.module").then(m => m.CountryInsightsModule)},
            {path: "addgovernmentfund",loadComponent: () => import("./founderstool/add-government-funding/add-government-funding.component").then(m => m.AddGovernmentFundingComponent)},
            {path: "entrprenuerskilltest",loadComponent: () => import("./founderstool/entrepreneurskilltest/entrepreneurskilltest.component").then(m => m.EntrepreneurskilltestComponent)},
            {path: "entrprenueurproficiencytest",loadComponent: () => import("./founderstool/entreprenuerproficiencytest/entreprenuerproficiencytest.component").then(m => m.EntreprenuerproficiencytestComponent)},
            {path: "entrprenueurquiz",loadComponent: () => import("./founderstool/entreprenuerquiz/entreprenuerquiz.component").then(m => m.EntreprenuerquizComponent)},
            {path: "addroles",component: RolesmanagementComponent},
            {path: "subscribers/datavalidator",loadComponent: () => import("./subscribers/datavalidator/datavalidator.component").then(m => m.DatavalidatorComponent)},
            {path: "advisor-chats",component: AdvisorChatComponent},
            {path: "sessionmanager",loadComponent: () => import("./session/sessionmanager/sessionmanager.component").then(m => m.SessionmanagerComponent)},
            {path: "sessionfeedbackform",loadComponent: () => import("./session/sessionfeedbackform/sessionfeedbackform.component").then(m => m.SessionfeedbackformComponent)},
            {path: "subscribers/datavalidator/uploaddetails",loadComponent: () => import("./subscribers/validationdata/validationdata.component").then(m => m.ValidationdataComponent)},
            {path: "assessment/scholarassessment",loadComponent: () => import("./assessment/student/student.component").then(m => m.studentComponent)},
            {path: "start-up-funding-hacks",loadComponent: () => import("./founderstool/addcomponent-stories-modules/addcomponent-stories-modules.component").then(m => m.AddcomponentStoriesModulesComponent)},
            {path: "start-up-success-stories",loadComponent: () => import("./founderstool/addcomponent-stories-modules/addcomponent-stories-modules.component").then(m => m.AddcomponentStoriesModulesComponent)},
            {path: "start-up-failure-stories",loadComponent: () => import("./founderstool/addcomponent-stories-modules/addcomponent-stories-modules.component").then(m => m.AddcomponentStoriesModulesComponent)},
            {path: "founders-success-stories",loadComponent: () => import("./founderstool/addcomponent-stories-modules/addcomponent-stories-modules.component").then(m => m.AddcomponentStoriesModulesComponent)},
            {path: "founders-failure-stories",loadComponent: () => import("./founderstool/addcomponent-stories-modules/addcomponent-stories-modules.component").then(m => m.AddcomponentStoriesModulesComponent)},
            {path: "travel-tools/travel-glossary",loadComponent: () => import("./travel-tools/travel-glossary/travel-glossary.component").then(m => m.TravelGlossaryComponent)},
            {path: "blogs",loadComponent: () => import("./blogsadmin/blogsadmin.component").then(m => m.BlogsadminComponent)},
            {path: "addblogs",loadComponent: () => import("./blogsadmin/addblogs/addblogs.component").then(m => m.AddblogsComponent)},
            {path: 'addblogs/:id',loadComponent: () => import('./blogsadmin/addblogs/addblogs.component').then(m => m.AddblogsComponent)},
            {path: 'management',loadComponent: () => import('./our-managements/our-managements.component').then(m => m.OurManagementsComponent)},
            {path: 'organization-details/:id',loadComponent: () => import('./partneruser/add-organization-users/add-organization-users.component').then(m => m.AddOrganizationUsersComponent)},
            {path: 'payout-manager',loadComponent: () => import('./payout-manager/payout-manager.component').then(m => m.PayoutManagerComponent)},
            {path: 'hiring-support',loadComponent: () => import('./hiring-support/hiring-support.component').then(m => m.HiringSupportComponent)},
            {path: 'career-coach',loadComponent: () => import('./career-coach/career-coach.component').then(m => m.CareerCoachComponent)},
            {path: 'employer-subscription',loadComponent: () => import('./employer-subscription/employer-subscription.component').then(m => m.EmployerSubscriptionComponent)},
            {path: 'employer-subscription-history',loadComponent: () => import('./employer-subscription/subscription-history/subscription-history.component').then(m => m.SubscriptionHistoryComponent)},
            {path: 'employer-subscription-view',loadComponent: () => import('./employer-subscription/employer-view/employer-view.component').then(m => m.EmployerViewComponent)},
            {path: 'talent-support',loadComponent: () => import('./talent-support/talent-support.component').then(m => m.TalentSupportComponent)},
            {path: 'jobs/view-jobs',loadComponent: () => import('./jobs/jobs.component').then(m => m.JobsComponent)},
            {path: 'jobs/create-job',loadComponent: () => import('./jobs/add-job/add-job.component').then(m => m.AddJobComponent)},
            {path: 'companies/view-companies',loadComponent: () => import('./companies/companies.component').then(m => m.CompaniesComponent)},
            {path: 'companies/create-company',loadComponent: () => import('./companies/add-company/add-company.component').then(m => m.AddCompanyComponent)},
            {path: 'companies/view-companies/:studentId',loadComponent: () => import('./companies/companies.component').then(m => m.CompaniesComponent)},
            {path: 'jobs/view-job/:companyId',loadComponent: () => import('./jobs/jobs.component').then(m => m.JobsComponent)},
            {path: 'talent-connect/talents/:companyId',loadComponent: () => import('./talent-connect/talents/talents.component').then(m => m.TalentsComponent)},
            {path: 'talent-connect/talents/:companySeen',loadComponent: () => import('./talent-connect/talents/talents.component').then(m => m.TalentsComponent)},
            {path: 'talent-connect/talents/:jobId',loadComponent: () => import('./talent-connect/talents/talents.component').then(m => m.TalentsComponent)},
            {path: "subscribers/:jobId",loadComponent: () => import("./subscribers/subscribers.component").then(m => m.SubscribersComponent)},
            {path: 'subscribers/:appliedJobId',loadComponent: () => import('./subscribers/subscribers.component').then(m => m.SubscribersComponent)},
        ]
    }
];
@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})
export class PagesRoutingModule {
}